bulidsepc_review.yml file modified

diff --git a/buildspec_review.yml b/buildspec_review.yml
--- a/buildspec_review.yml
+++ b/buildspec_review.yml
@@ -26,7 +26,8 @@ phases:
       - ls -l $CODEBUILD_SRC_DIR/sonar-scanner-5.0.1.3006-linux/bin/
       
       # Execute SonarScanner command
-      - sonar-scanner -X \
+      - |
+        sonar-scanner -X \
         -Dsonar.login=$LOGIN \
         -Dsonar.host.url=$HOST \
         -Dsonar.projectKey=$Project \
@@ -39,10 +40,14 @@ phases:
       # Check the quality gate status
       - echo "Curl command:"
       - echo "curl -u $LOGIN https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project -o result.json"
-      - curl -u $LOGIN https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project -o result.json || echo "Curl failed with error code: $?"
+      - |
+        curl -u $LOGIN https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project -o result.json || echo "Curl failed with error code: $?"
 
       # Display the content of the result file for debugging
       - cat result.json || echo "Unable to read result.json file"
 
       # Fail the build if the quality gate status is not "OK"
-      - if [ "$(jq -r '.projectStatus.status' result.json)" != "OK" ]; then exit 1; fi
+      - |
+        if [ "$(jq -r '.projectStatus.status' result.json)" != "OK" ]; then
+          exit 1
+        fi
